/**
 * ax_runtime.h — AXIOM Unified C Runtime Header
 *
 * Every .c file generated by the AXIOM C-Backend begins with:
 *   #include "ax_runtime.h"
 *
 * This header provides all primitive type definitions, allocator access,
 * generational reference functions, panic handling, and utility macros.
 *
 * Include order:
 *   1. System headers
 *   2. Primitive type aliases
 *   3. String type
 *   4. Runtime subsystems (allocator, genref, panic)
 *   5. Slice types
 *   6. Utility macros
 *   7. Entry point wrapper (conditional)
 */
#pragma once

/* ================================================================
 * 1. System headers
 * ================================================================ */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* ================================================================
 * 2. Primitive type aliases (AXIOM → C)
 * ================================================================ */

/* Signed integers */
typedef int8_t   ax_i8;
typedef int16_t  ax_i16;
typedef int32_t  ax_i32;
typedef int64_t  ax_i64;

/* Unsigned integers */
typedef uint8_t  ax_u8;
typedef uint16_t ax_u16;
typedef uint32_t ax_u32;
typedef uint64_t ax_u64;

/* Floating point */
typedef float    ax_f32;
typedef double   ax_f64;

/* Boolean */
typedef _Bool    ax_bool;
#define AX_TRUE  ((ax_bool)1)
#define AX_FALSE ((ax_bool)0)

/* Platform-sized integers */
typedef intptr_t  ax_isize;
typedef uintptr_t ax_usize;

/* Byte and char */
typedef uint8_t  ax_byte;
typedef uint32_t ax_char; /* Unicode scalar value (U+0000..U+10FFFF) */

/* ================================================================
 * 3. String type
 * ================================================================ */

/**
 * ax_string — Immutable length-prefixed UTF-8 byte slice.
 * Not null-terminated.
 */
typedef struct {
    const ax_u8* ptr;  /* pointer to UTF-8 bytes */
    ax_u64       len;  /* byte length */
} ax_string;

/** Convenience macro for string literals */
#define AX_STR(literal) \
    ((ax_string){ .ptr = (const ax_u8*)(literal), .len = sizeof(literal) - 1 })

/* ================================================================
 * 4. Runtime subsystems
 * ================================================================ */
#include "axalloc/axalloc.h"
/* Note: axalloc.h includes genref.h at the bottom */
#include "panic/panic.h"

/* ================================================================
 * 5. Slice types
 * ================================================================ */

/** Declare a concrete slice type for element type T */
#define AX_SLICE_DECL(T, name) \
    typedef struct { T* ptr; ax_u64 len; ax_u64 cap; } name

/* Pre-declared common slice types */
AX_SLICE_DECL(ax_i8,   ax_slice_i8);
AX_SLICE_DECL(ax_i16,  ax_slice_i16);
AX_SLICE_DECL(ax_i32,  ax_slice_i32);
AX_SLICE_DECL(ax_i64,  ax_slice_i64);
AX_SLICE_DECL(ax_u8,   ax_slice_u8);
AX_SLICE_DECL(ax_u16,  ax_slice_u16);
AX_SLICE_DECL(ax_u32,  ax_slice_u32);
AX_SLICE_DECL(ax_u64,  ax_slice_u64);
AX_SLICE_DECL(ax_f32,  ax_slice_f32);
AX_SLICE_DECL(ax_f64,  ax_slice_f64);
AX_SLICE_DECL(ax_byte, ax_slice_byte);

/* ================================================================
 * 6. Utility macros
 * ================================================================ */

/** Silence unused variable warnings */
#define AX_UNUSED(x)       ((void)(x))

/** Branch prediction hints */
#ifndef AX_LIKELY
  #if defined(__GNUC__) || defined(__clang__)
    #define AX_LIKELY(x)   __builtin_expect(!!(x), 1)
  #else
    #define AX_LIKELY(x)   (x)
  #endif
#endif

#ifndef AX_UNLIKELY
  #if defined(__GNUC__) || defined(__clang__)
    #define AX_UNLIKELY(x) __builtin_expect(!!(x), 0)
  #else
    #define AX_UNLIKELY(x) (x)
  #endif
#endif

/** Static array length */
#define AX_ARRAY_LEN(arr)  (sizeof(arr) / sizeof((arr)[0]))

/** Type-safe min/max */
#define AX_MIN(a, b) ((a) < (b) ? (a) : (b))
#define AX_MAX(a, b) ((a) > (b) ? (a) : (b))

/** Compile-time assertion */
#define AX_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)

/* ================================================================
 * 7. Entry point wrapper (conditional)
 *
 * The C-Backend defines AX_EMIT_MAIN in exactly one compilation
 * unit per binary (the file containing fn main()). This emits
 * a C main() that initializes the runtime and calls ax_main().
 * ================================================================ */
#ifdef AX_EMIT_MAIN
#ifdef AX_MAIN_WITH_ARGS
extern int ax_main(ax_i32 argc, ax_u8** argv);
#else
extern int ax_main(void);
#endif

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#endif

int main(int argc, char** argv) {
#ifdef _WIN32
    SetConsoleOutputCP(65001);
#endif
    ax_set_program_name(argc > 0 ? argv[0] : "<axiom>");
#ifdef AX_MAIN_WITH_ARGS
    return ax_main((ax_i32)argc, (ax_u8**)argv);
#else
    (void)argc;
    (void)argv;
    return ax_main();
#endif
}
#endif

