#!/usr/bin/env python3
# Oracle-based verification generator for std.math.
# Computes reference values with Python's math module across a grid per function,
# then emits a bundled AXIOM program (std/math.ax + a main of unrolled relative-
# error checks). Exit code = number of functions with ANY point exceeding its
# tolerance (0 = all accurate). Run: python gen_verify.py > out.ax ; build+run.
import math, io, sys

# (axiom_name, python_callable, [points], rel_tol)
def lin(a, b, n):
    return [a + (b - a) * i / (n - 1) for i in range(n)]

FUNCS = [
    ("sin",   math.sin,                lin(-3.0, 3.0, 9), 1e-6),
    ("cos",   math.cos,                lin(-3.0, 3.0, 9), 1e-6),
    ("tan",   math.tan,                lin(-1.0, 1.0, 9), 1e-6),
    ("exp",   math.exp,                lin(-3.0, 3.0, 9), 1e-6),
    ("ln",    math.log,                lin(0.1, 50.0, 9), 1e-6),
    ("log2",  math.log2,               lin(0.1, 50.0, 9), 1e-6),
    ("log10", math.log10,              lin(0.1, 50.0, 9), 1e-6),
    ("sqrt",  math.sqrt,               lin(0.0, 100.0, 9), 1e-6),
    ("cbrt",  lambda x: x ** (1/3),    lin(0.0, 100.0, 9), 1e-6),
    ("exp2",  lambda x: 2.0 ** x,      lin(-5.0, 5.0, 9), 1e-6),
    ("asin",  math.asin,               lin(-0.95, 0.95, 9), 1e-6),
    ("acos",  math.acos,               lin(-0.95, 0.95, 9), 1e-6),
    ("atan",  math.atan,               lin(-5.0, 5.0, 9), 1e-6),
    ("sinh",  math.sinh,               lin(-3.0, 3.0, 9), 1e-6),
    ("cosh",  math.cosh,               lin(-3.0, 3.0, 9), 1e-6),
    ("tanh",  math.tanh,               lin(-3.0, 3.0, 9), 1e-6),
    ("asinh", math.asinh,              lin(-3.0, 3.0, 9), 1e-6),
    ("acosh", math.acosh,              lin(1.1, 10.0, 9), 1e-6),
    ("atanh", math.atanh,              lin(-0.9, 0.9, 9), 1e-6),
    ("erf",   math.erf,                lin(-3.0, 3.0, 9), 1e-6),
    ("erfc",  math.erfc,               lin(-3.0, 3.0, 9), 1e-6),
    ("tgamma", math.gamma,             lin(0.5, 6.0, 9), 1e-6),
    ("lgamma", math.lgamma,            lin(0.5, 20.0, 9), 1e-6),
]

def fmt(x):
    # Fixed-point decimal (no exponent — AXIOM lexer has no e-notation), and
    # wrap negatives as (0.0 - a) so there is no bare unary minus literal.
    x = float(x)
    if x < 0:
        return "(0.0 - %s)" % ("%.20f" % (-x))
    return "%.20f" % x

out = io.StringIO()
out.write("// AUTO-GENERATED by tests/mathlib/gen_verify.py — do not edit.\n")
out.write("// Exit = number of std.math functions exceeding tolerance (0 = all OK).\n\n")
out.write("fn rel_bad(got: f64, ref: f64, tol: f64) -> i32:\n")
out.write("    mut e := got - ref\n")
out.write("    if e < 0.0:\n        e = 0.0 - e\n")
out.write("    mut den := ref\n")
out.write("    if den < 0.0:\n        den = 0.0 - den\n")
out.write("    if den < 1.0:\n        den = 1.0\n")
out.write("    if e / den > tol:\n        return 1 as i32\n")
out.write("    return 0 as i32\n\n")
out.write("pub fn main() -> i32:\n")
out.write("    mut funcs_bad := 0 as i32\n")
for name, fn, pts, tol in FUNCS:
    out.write("    mut b_%s := 0 as i32\n" % name)
    for x in pts:
        try:
            ref = fn(x)
        except Exception:
            continue
        if not math.isfinite(ref):
            continue
        out.write("    b_%s = b_%s + rel_bad(%s(%s), %s, %s)\n"
                  % (name, name, name, fmt(x), fmt(ref), fmt(tol)))
    out.write("    if b_%s > 0 as i32:\n        funcs_bad = funcs_bad + 1 as i32\n" % name)
out.write("    return funcs_bad\n")

sys.stdout.write(out.getvalue())
