#!/usr/bin/env bash
# Regression gate for the known-bug repros (chain #24..#31 + Family C / RFC 0001).
# Run after ANY codegen/optimizer/ABI change before trusting the next step.
# Each case: build with the given compiler (default bin/axc_stage1.exe) at -O1,
# run, and compare stdout (CMP=out) or exit code (CMP=exit) to the expected value.
#
# NOTE: on this Windows box, Windows Defender realtime adds ~50s per self-link
# build (CPU ~0, pure scan). That is NOT a hang — keep the per-build timeout >=120s.
set -u
cd "$(dirname "$0")/.."
AXC="${AXC:-bin/axc_stage1.exe}"
TIMEOUT="${TIMEOUT:-150}"
pass=0; fail=0; failed=""

# rows: name | cmp(out|exit) | expected
rows=(
  "tsp|exit|7"
  "tsp2|exit|9"
  "tsp3|exit|12"
  "tstruct_abi|out|A=7 B=12 C=15 D=6 E=99 "
  "t_movrr|out|072 137 229 "
  "t_modrm|out|229"
  "t_cp2|out|7"
  "t_cpaddr|exit|7"
  "t_cse|exit|98"
  "t_param5|out|A38"
  "t_strip|out|a.b len exit print"
  "t_alias|out|A=1 B=0 "
  "t_mutstr|exit|9"
  "t_method|exit|24"
  "t_enum_np|exit|6"
  "t_enum|exit|42"
  "t_adt2|exit|104"
  "t_adt3|exit|19"
  "t_builtin_opt|exit|15"
  "t_litinfer|exit|111"
  "t_udiv|exit|5"
  "t_ucmp|exit|6"
  "t_f32|exit|5"
  "t_switch|exit|4"
  "t_cassign|exit|12"
  "t_unsafe|exit|20"
  "t_pow|exit|59"
  "t_defer|exit|7"
  "t_mask|exit|15"
  "t_opover|exit|44"
  "t_bytes|exit|69"
  "t_u128|exit|91"
  "t_opmix|exit|13"
  "t_mul128|exit|7"
  "t_fcmp|exit|15"
  # t_farg returns 300, but bash $? is 8-bit: 300 & 0xFF = 44. 65a17b8 set 300
  # (verified under PowerShell, full 32-bit exit) which can never pass HERE.
  "t_farg|exit|44"
  "t_fret|exit|75"
  "t_math|exit|127"
  "t_bignum|exit|63"
  "t_bn256|exit|31"
  "t_bf128|exit|15"
  "t_bndyn|exit|99"
  "t_mathx|exit|28"
  "t_b44|exit|54"
  "t_erf|exit|15"
  "t_gamma|exit|63"
  "t_complex|exit|63"
  "t_vec|exit|63"
  "t_stats|exit|63"
  "t_numtheory|exit|127"
  "t_combinatorics|exit|127"
  "t_interpolation|exit|127"
  "t_geometry|exit|127"
  "t_probability|exit|127"
  "t_numtheory2|exit|127"
  "t_coordinates|exit|127"
  "t_color|exit|127"
  "t_statx|exit|127"
  "t_signal|exit|127"
  "t_ml|exit|127"
  "t_mathfill|exit|127"
  "t_bitmath|exit|127"
  "t_millerrabin|exit|127"
  "t_special|exit|127"
  "t_numerical|exit|127"
  "t_geometry2|exit|127"
  "t_colorhsl|exit|127"
  "t_rng|exit|127"
  "t_decimal|exit|127"
  "t_quaternion|exit|127"
  "t_matrix|exit|127"
  "t_vec4|exit|127"
  "t_fspill|exit|78"
  "t_fctor|exit|40"
  "t_ffree|exit|110"
  "fmeth|exit|110"
  "fsmall|exit|37"
  "t_trecip|exit|8"
  "t_ieeerem|exit|8"
  "t_zeta|exit|5"
  "t_quatrot|exit|8"
  "t_fft|exit|18"
  "fp0i|exit|5"
  "fpBi|exit|5"
  "fpf|exit|14"
  "t_nmf|exit|9"
  "t_numeric|exit|5"
  "t_sort|exit|4"
  "t_qsort|exit|6"
  "t_sort2|exit|5"
  "t_func|exit|6"
  "t_lambda|exit|5"
  "t_modcollide|exit|101"
  "t_hashi64|exit|42"
  "t_nestedgen|exit|42"
  "t_optstruct|exit|40"
  "t_optnested|exit|42"
  "t_structeq|exit|42"
  "t_arrlit|exit|15"
  "t_closurecap|exit|6"
  "t_genericstruct2|exit|40"
  "t_mutparam|exit|22"
  "t_structarrfield|exit|119"
  "t_retstructfield|exit|11"
  "t_nested3field|exit|13"
  "t_arroption|exit|110"
  "t_vecoption|exit|110"
  "t_ovcollide|exit|37"
  "t_variantstruct|exit|17"
  "t_underscore|exit|27"
  "t_arrelemaddr|exit|66"
  "t_fldelemaddr|exit|150"
  "t_forrange|exit|28"
  "t_forcollect|exit|56"
  "t_forcontinue|exit|52"
  "t_forstruct|exit|129"
  "t_forsum|exit|46"
  "t_mfvariant|exit|137"
  "t_strvariant|exit|44"
  "t_selftype|exit|13"
  "t_gensumctor|exit|54"
  "t_optmethod|exit|42"
  "t_strconcat|exit|15"
  "t_globals|exit|113"
  "sc1|exit|42"
  "sc2|exit|42"
  "scv|exit|3"
  "scw|exit|5"
  "scstress|exit|32"
  "t_matchret|exit|30"
  "t_missingret|reject|"
  "t_partialmatch|reject|"
  "t_forvec|exit|60"
  "t_rune|exit|65"
  "t_bytesview|exit|204"
  "t_forbytes|exit|198"
  "t_forstr|exit|15"
  "t_strslice|exit|142"
  "t_strmethod|exit|147"
  "t_strsplit|exit|46"
  "t_strutf8|exit|74"
  "t_tostr|exit|88"
  "t_tostru64|exit|19"
  "t_tostrf|exit|91"
  "t_tohex|exit|123"
  "t_toradix|exit|99"
  "t_numufcs|exit|11"
  "t_numufcsneg|reject|"
  "t_numufcswide|exit|7"
  "t_strviews|exit|244"
  "t_geninstfield|exit|44"
  "t_cseredef|exit|12"
  "t_hashiter|exit|15"
  "t_hashcontainskey|exit|7"
  "t_crosstypereject|reject|"
  "t_vecoptmatch|exit|42"
  "t_genfieldufcs|exit|4"
  "t_sumdispatch|exit|31"
  "t_optunwrapadd|exit|112"
  "t_optarithreject|reject|"
  "t_arrret|exit|70"
  "t_arrargmismatch|reject|"
  "t_ctorarrfield|exit|110"
  "t_freefncollision|exit|15"
  "t_freefncollision_arity|exit|105"
  "t_inlinearmstmt|reject|"
  "t_optstrmatch|exit|10"
  "t_gentree|exit|15"
  "t_variantshadow|reject|"
  "t_nomethod|reject|"
  "t_nonexhenum|reject|"
  "t_exhaustenum|exit|3"
  "t_arityfew|reject|"
  "t_aritymany|reject|"
  "t_arityok|exit|21"
  "t_badfield|reject|"
  "t_goodfield|exit|5"
  "t_vecindex|exit|7"
  "t_vecset|exit|42"
  "t_scalarmember|reject|"
  "t_floatneg|exit|74"
  "t_constshift|exit|35"
  "t_methodmany|reject|"
  "t_methodfew|reject|"
  "t_methodok|exit|40"
  "t_forgotunwrap|reject|"
  "t_unwrapok|exit|42"
  "t_staticcall|exit|41"
  "t_globalinit|exit|210"
  "t_bracelit|reject|"
  "t_optarray|exit|40"
  "t_resultarray|exit|40"
  "t_optarrayiter|exit|123"
  "t_optarraymethod|exit|40"
  "t_structoptfield|exit|42"
  "t_vecvec|exit|42"
  "t_hashvecval|exit|42"
  "t_optresult|exit|42"
  "t_vecstructopt|exit|42"
  "t_matchshadow|exit|42"
  # feature-combo probe oracles (banked 2026-07-12, batch 7)
  "t_genpairopt|exit|77"
  "t_arrstructidx|exit|102"
  "t_negdivmod|exit|25"
  "t_scshortcirc|exit|12"
  "t_genfnopt|exit|63"
  "t_strfieldcat|exit|5"
  "t_resstrmatch|exit|3"
  "t_treeoptchild|exit|15"
  "t_nestbreakcont|exit|16"
  "t_hashstrkey|exit|30"
  "t_u64cmp|exit|7"
  "t_optveciter|exit|6"
  "t_deepopt|exit|99"
  # RFC 0017 P2 — aggregate (struct/array/tuple) module-level globals
  "t_globstruct|exit|30"
  "t_globarr|exit|80"
  "t_globnested|exit|40"
  "t_globarriter|exit|119"
  "t_globbig|exit|65"
  "t_globpass|exit|42"
  # RFC 0017 P2 — aggregate-global interaction surface
  "t_globarrstruct|exit|118"
  "t_globmethod|exit|42"
  "t_globgeneric|exit|42"
  "t_globmixed|exit|40"
  "t_globi32arr|exit|130"
  "t_globstrfield|exit|10"
  # RFC 0017 — no-initializer globals default to a zeroed .data slot (parser desync fix)
  "t_globnoinit|exit|7"
  "t_globstructnoinit|exit|42"
  "t_globarrnoinit|exit|40"
  # RFC 0017 P2 — aggregate-global write paths (user-code block-copy, not just init)
  "t_globwholeassign|exit|42"
  "t_globg2g|exit|42"
  "t_globreturn|exit|42"
  "t_globrmwloop|exit|20"
  "t_globarrfn|exit|50"
  "t_globopt|exit|42"
  "t_globresult|exit|42"
  "t_globsum|exit|42"
  "t_globstr|exit|42"
  "t_globstridx|exit|42"
  # RFC 0017 P2 — str/16B-inline & pointer-repr embedded inside aggregate globals (deep crosses)
  "t_globarrstr|exit|15"
  "t_globoptstr|exit|8"
  "t_globarrstructstr|exit|20"
  "t_globarropt|exit|22"
  "t_globinitorder|exit|40"
  # RFC 0022 — tuple literal expressions (anonymous struct + .N access)
  "t_tuple|exit|66"
  # RFC 0022 P2 — tuple TYPE annotations: annotated let / return / param / global
  "t_tuple2|exit|84"
  # RFC 0022 P3 — tuple destructuring `let (a, b) = EXPR` (single-eval + wildcard + mut)
  "t_tuple3|exit|50"
  # RFC 0022 P4 — chained tuple field access `t.N.M` (float-selector split)
  "t_tuple4|exit|10"
  # RFC 0022 — tuple-typed struct field (ctor-field element coercion)
  "t_tupfield|exit|33"
)

for row in "${rows[@]}"; do
  IFS='|' read -r name cmp want <<< "$row"
  src="bin/${name}.ax"
  [ -f "$src" ] || { echo "SKIP $name (no $src)"; continue; }
  out_exe="/tmp/reg_${name}.exe"
  rm -f "$out_exe"
  timeout "$TIMEOUT" "$AXC" build "$src" -o "$out_exe" -O1 >/dev/null 2>&1
  if [ "$cmp" = "reject" ]; then
    # Expect the compiler to REJECT this program (diagnostic, no exe emitted).
    if [ ! -f "$out_exe" ]; then echo "PASS $name (rejected)"; pass=$((pass+1)); else echo "FAIL $name (expected rejection, got exe)"; fail=$((fail+1)); failed="$failed $name"; fi
    continue
  fi
  if [ ! -f "$out_exe" ]; then echo "FAIL $name (build produced no exe)"; fail=$((fail+1)); failed="$failed $name"; continue; fi
  got_out=$("$out_exe" 2>/dev/null); got_exit=$?
  if [ "$cmp" = "exit" ]; then got="$got_exit"; else got="$got_out"; fi
  if [ "$got" = "$want" ]; then
    echo "PASS $name ($cmp=$got)"; pass=$((pass+1))
  else
    echo "FAIL $name ($cmp: got '$got' want '$want')"; fail=$((fail+1)); failed="$failed $name"
  fi
done

echo "=== regression: $pass passed, $fail failed ==="
[ -n "$failed" ] && echo "FAILED:$failed"
[ "$fail" -eq 0 ] && echo "REGRESSION_OK" || echo "REGRESSION_FAIL"
