package pkg

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"strings"
)

type LockedPackage struct {
	Name    string
	Version string
	Source  string
	Commit  string
	Sha256  string
}

type Lockfile struct {
	Packages []LockedPackage
}

// ParseLockfile parses axiom.lock file content and returns a Lockfile struct.
// It uses a custom, lightweight TOML parser specifically tailored for the list of packages inside axiom.lock.
func ParseLockfile(content string) (*Lockfile, error) {
	lock := &Lockfile{}
	lines := strings.Split(content, "\n")
	var currentPkg *LockedPackage

	for lineNum, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		if line == "[[package]]" {
			if currentPkg != nil {
				lock.Packages = append(lock.Packages, *currentPkg)
			}
			currentPkg = &LockedPackage{}
			continue
		}

		eqIdx := strings.Index(line, "=")
		if eqIdx == -1 {
			return nil, fmt.Errorf("line %d: invalid syntax (missing '=')", lineNum+1)
		}

		key := strings.TrimSpace(line[:eqIdx])
		valStr := strings.TrimSpace(line[eqIdx+1:])

		if currentPkg == nil {
			return nil, fmt.Errorf("line %d: fields must be declared inside a [[package]] block", lineNum+1)
		}

		val, err := parseString(valStr)
		if err != nil {
			return nil, fmt.Errorf("line %d: invalid value for %s: %v", lineNum+1, key, err)
		}

		switch key {
		case "name":
			currentPkg.Name = val
		case "version":
			currentPkg.Version = val
		case "source":
			currentPkg.Source = val
		case "commit":
			currentPkg.Commit = val
		case "sha256":
			currentPkg.Sha256 = val
		default:
			return nil, fmt.Errorf("line %d: unknown lockfile field %q", lineNum+1, key)
		}
	}

	if currentPkg != nil {
		lock.Packages = append(lock.Packages, *currentPkg)
	}

	return lock, nil
}

// SerializeLockfile serializes a Lockfile struct into a formatted TOML string.
func SerializeLockfile(lock *Lockfile) (string, error) {
	var sb strings.Builder
	sb.WriteString("# This file is automatically generated by AXIOM.\n")
	sb.WriteString("# Manual edits may be overwritten.\n\n")

	for _, pkg := range lock.Packages {
		sb.WriteString("[[package]]\n")
		sb.WriteString(fmt.Sprintf("name = %q\n", pkg.Name))
		sb.WriteString(fmt.Sprintf("version = %q\n", pkg.Version))
		sb.WriteString(fmt.Sprintf("source = %q\n", pkg.Source))
		sb.WriteString(fmt.Sprintf("commit = %q\n", pkg.Commit))
		sb.WriteString(fmt.Sprintf("sha256 = %q\n\n", pkg.Sha256))
	}

	return sb.String(), nil
}

// CalculateDirSHA256 computes a SHA-256 hash of a directory by hashing all its files sorted alphabetically.
// This is used to verify cache directory integrity.
func CalculateDirSHA256(dirPath string) (string, error) {
	hasher := sha256.New()
	err := filepathWalk(dirPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}

		// Read file contents and write to hash
		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer f.Close()

		// Include relative path in the hash to protect against file renaming/restructuring
		if relPath, err := filepathRel(dirPath, path); err == nil {
			hasher.Write([]byte(relPath))
		}

		if _, err := io.Copy(hasher, f); err != nil {
			return err
		}
		return nil
	})

	if err != nil {
		return "", err
	}

	return hex.EncodeToString(hasher.Sum(nil)), nil
}

// Simple path helpers to avoid external os/filepath package inconsistencies
func filepathWalk(root string, walkFn func(path string, info os.FileInfo, err error) error) error {
	info, err := os.Lstat(root)
	if err != nil {
		return walkFn(root, nil, err)
	}
	return walk(root, info, walkFn)
}

func walk(path string, info os.FileInfo, walkFn func(path string, info os.FileInfo, err error) error) error {
	err := walkFn(path, info, nil)
	if err != nil {
		if info.IsDir() && err == filepathSkipDir {
			return nil
		}
		return err
	}

	if !info.IsDir() {
		return nil
	}

	names, err := readDirNames(path)
	if err != nil {
		return walkFn(path, nil, err)
	}

	for _, name := range names {
		filename := path + string(os.PathSeparator) + name
		fileInfo, err := os.Lstat(filename)
		if err != nil {
			if err := walkFn(filename, nil, err); err != nil && err != filepathSkipDir {
				return err
			}
		} else {
			err = walk(filename, fileInfo, walkFn)
			if err != nil {
				if !fileInfo.IsDir() || err != filepathSkipDir {
					return err
				}
			}
		}
	}
	return nil
}

var filepathSkipDir = fmt.Errorf("skip this directory")

func readDirNames(dirname string) ([]string, error) {
	f, err := os.Open(dirname)
	if err != nil {
		return nil, err
	}
	list, err := f.Readdirnames(-1)
	f.Close()
	if err != nil {
		return nil, err
	}
	return list, nil
}

func filepathRel(basepath, targpath string) (string, error) {
	// Simple fallbacks for absolute pathsrel calculations
	basepath = strings.ReplaceAll(basepath, "\\", "/")
	targpath = strings.ReplaceAll(targpath, "\\", "/")
	if strings.HasPrefix(targpath, basepath) {
		rel := targpath[len(basepath):]
		if strings.HasPrefix(rel, "/") {
			rel = rel[1:]
		}
		return rel, nil
	}
	return targpath, nil
}
